import 'models/lailyfa_febrina_card_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:blackevil2401_s_application3/widgets/custom_elevated_button.dart';import 'package:blackevil2401_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'provider/lailyfa_febrina_card_provider.dart';class LailyfaFebrinaCardScreen extends StatefulWidget {const LailyfaFebrinaCardScreen({Key? key}) : super(key: key);

@override LailyfaFebrinaCardScreenState createState() =>  LailyfaFebrinaCardScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => LailyfaFebrinaCardProvider(), child: LailyfaFebrinaCardScreen()); } 
 }
class LailyfaFebrinaCardScreenState extends State<LailyfaFebrinaCardScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 18.v), child: Column(children: [SizedBox(height: 19.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 15.h, right: 15.h, bottom: 5.v), child: Column(children: [_buildCreditCard(context), SizedBox(height: 23.v), _buildCardNumber(context), SizedBox(height: 24.v), _buildExpirationDate(context), SizedBox(height: 29.v), _buildSecurityCode(context), SizedBox(height: 23.v), _buildCardHolder(context)]))))])), bottomNavigationBar: _buildSave(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 14.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "msg_lailyfa_febrina".tr, margin: EdgeInsets.only(left: 12.h))); } 
/// Section Widget
Widget _buildCreditCard(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 23.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 22.v, width: 36.h, margin: EdgeInsets.only(left: 3.h)), SizedBox(height: 30.v), Text("msg_6326_9124".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), fontSize: 24.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 17.v), Row(children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.5, child: Text("lbl_card_holder".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer, fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), SizedBox(height: 4.v), Text("lbl_lailyfa_febrina".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))])), Padding(padding: EdgeInsets.only(left: 27.h, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.5, child: Text("lbl_card_save".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer, fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_06_24".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)))]))])])); } 
/// Section Widget
Widget _buildCardNumber(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_card_number".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<LailyfaFebrinaCardProvider, TextEditingController?>(selector: (context, provider) => provider.cardNumberController, builder: (context, cardNumberController, child) {return CustomTextFormField(controller: cardNumberController, hintText: "msg_1231_2312_3123".tr);}))]); } 
/// Section Widget
Widget _buildExpirationDate(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_expiration_date".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<LailyfaFebrinaCardProvider, TextEditingController?>(selector: (context, provider) => provider.expirationDateController, builder: (context, expirationDateController, child) {return CustomTextFormField(controller: expirationDateController, hintText: "lbl_12_12".tr);}))]); } 
/// Section Widget
Widget _buildSecurityCode(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_security_code".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 11.v), Selector<LailyfaFebrinaCardProvider, TextEditingController?>(selector: (context, provider) => provider.securityCodeController, builder: (context, securityCodeController, child) {return CustomTextFormField(controller: securityCodeController, hintText: "lbl_1219".tr);})]); } 
/// Section Widget
Widget _buildCardHolder(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_card_holder2".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<LailyfaFebrinaCardProvider, TextEditingController?>(selector: (context, provider) => provider.cardHolderNameController, builder: (context, cardHolderNameController, child) {return CustomTextFormField(controller: cardHolderNameController, hintText: "lbl_lailyfa_febrina".tr, textInputAction: TextInputAction.done);}))]); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 50.v), onPressed: () {onTapSave(context);}); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the creditCardAndDebitScreen when the action is triggered.
onTapSave(BuildContext context) { NavigatorService.pushNamed(AppRoutes.creditCardAndDebitScreen, ); } 
 }
