import 'models/list_category_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/list_category_provider.dart';class ListCategoryScreen extends StatefulWidget {const ListCategoryScreen({Key? key}) : super(key: key);

@override ListCategoryScreenState createState() =>  ListCategoryScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ListCategoryProvider(), child: ListCategoryScreen()); } 
 }
class ListCategoryScreenState extends State<ListCategoryScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 10.v), child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgArrowRight, bikiniText: "lbl_shirt".tr, onTapBikiniIcon: () {onTapBikiniIcon(context);}), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgBikiniIcon, bikiniText: "lbl_bikini".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgDressIcon, bikiniText: "lbl_dress".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgManWorkEquipment, bikiniText: "lbl_work_equipment".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgManPantsIcon, bikiniText: "lbl_man_pants".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgManShoesIcon, bikiniText: "lbl_man_shoes".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgManUnderwearIcon, bikiniText: "lbl_man_underwear".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgManTShirtIcon, bikiniText: "lbl_man_t_shirt".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgWomanBagIcon, bikiniText: "lbl_woman_bag".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgWomanPantsIcon, bikiniText: "lbl_woman_pants".tr), _buildCategoryOptionBikini(context, bikiniIcon: ImageConstant.imgHighHeelsIcon, bikiniText: "lbl_high_heels".tr)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 14.v, bottom: 17.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "lbl_category".tr, margin: EdgeInsets.only(left: 12.h))); } 
/// Common widget
Widget _buildCategoryOptionBikini(BuildContext context, {required String bikiniIcon, required String bikiniText, Function? onTapBikiniIcon, }) { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnPrimaryContainer, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: bikiniIcon, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapBikiniIcon!.call();}), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v, bottom: 3.v), child: Text(bikiniText, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 

/// Navigates to the previous screen.
onTapBikiniIcon(BuildContext context) { NavigatorService.goBack(); } 
 }
