import 'offerbanner_item_model.dart';import '../../../core/app_export.dart';import 'arrowright_item_model.dart';import 'productitem_item_model.dart';import 'megasaleheader_item_model.dart';import 'products_item_model.dart';class DashboardModel {List<OfferbannerItemModel> offerbannerItemList = List.generate(1,(index) => OfferbannerItemModel());

List<ArrowrightItemModel> arrowrightItemList = [ArrowrightItemModel(arrowRight:ImageConstant.imgArrowRight,manShirt: "Man Shirt"),ArrowrightItemModel(arrowRight:ImageConstant.imgManWorkEquipment,manShirt: "Office Bag"),ArrowrightItemModel(arrowRight:ImageConstant.imgDressIcon,manShirt: "Dress"),ArrowrightItemModel(arrowRight:ImageConstant.imgWomanBagIcon,manShirt: "Woman Bag"),ArrowrightItemModel(arrowRight:ImageConstant.imgManShoesIcon,manShirt: "Man Shoes")];

List<ProductitemItemModel> productitemItemList = [ProductitemItemModel(image:ImageConstant.imgProductImage,fSNikeAirMax: "FS - Nike Air Max 270 React...",price: "299,43",price1: "534,33",offer: "24% Off"),ProductitemItemModel(image:ImageConstant.imgProductImage109x109,fSNikeAirMax: "FS - QUILTED MAXI CROS...",price: "299,43",price1: "534,33",offer: "24% Off"),ProductitemItemModel(image:ImageConstant.imgProductImage1,fSNikeAirMax: "FS - Nike Air Max 270 React...",price: "299,43",price1: "534,33",offer: "24% Off")];

List<MegasaleheaderItemModel> megasaleheaderItemList = [MegasaleheaderItemModel(image:ImageConstant.imgProductImage2,mSNikeAirMax: "MS - Nike Air Max 270 React...",price: "299,43",price1: "534,33",offer: "24% Off"),MegasaleheaderItemModel(image:ImageConstant.imgProductImage3,mSNikeAirMax: "MS - Nike Air Max 270 React...",price: "299,43",price1: "534,33",offer: "24% Off"),MegasaleheaderItemModel(image:ImageConstant.imgProductImage4,mSNikeAirMax: "MS - Nike Air Max 270 React...",price: "299,43",price1: "534,33",offer: "24% Off")];

List<ProductsItemModel> productsItemList = [ProductsItemModel(image:ImageConstant.imgImageProduct,nikeAirMaxReact: "Nike Air Max 270 React ENG",price: "299,43",price1: "534,33",offer: "24% Off"),ProductsItemModel(image:ImageConstant.imgProductImage2,nikeAirMaxReact: "Nike Air Max 270 React ENG",price: "299,43",price1: "534,33",offer: "24% Off"),ProductsItemModel(image:ImageConstant.imgProductImage133x133,nikeAirMaxReact: "Nike Air Max 270 React ENG",price: "299,43",price1: "534,33",offer: "24% Off"),ProductsItemModel(image:ImageConstant.imgProductImage1,nikeAirMaxReact: "Nike Air Max 270 React ENG",price: "299,43",price1: "534,33",offer: "24% Off")];

 }
