import 'models/notification_feed_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/notification_feed_provider.dart';class NotificationFeedScreen extends StatefulWidget {const NotificationFeedScreen({Key? key}) : super(key: key);

@override NotificationFeedScreenState createState() =>  NotificationFeedScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => NotificationFeedProvider(), child: NotificationFeedScreen()); } 
 }
class NotificationFeedScreenState extends State<NotificationFeedScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 11.v), child: Column(children: [_buildFeedItemRow(context, productImage: ImageConstant.imgProductImage, bestProductText: "lbl_new_product".tr, productDescriptionText: "msg_nike_air_zoom_pegasus2".tr, dateText: "msg_june_3_2015_5_06".tr), _buildFeedItemRow(context, productImage: ImageConstant.imgImageProduct, bestProductText: "lbl_best_product".tr, productDescriptionText: "msg_nike_air_zoom_pegasus2".tr, dateText: "msg_june_3_2015_5_06".tr), SizedBox(height: 5.v), _buildFeedItemRow(context, productImage: ImageConstant.imgProductImage1, bestProductText: "lbl_new_product".tr, productDescriptionText: "msg_nike_air_zoom_pegasus2".tr, dateText: "msg_june_3_2015_5_06".tr)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "lbl_feed".tr, margin: EdgeInsets.only(left: 12.h))); } 
/// Common widget
Widget _buildFeedItemRow(BuildContext context, {required String productImage, required String bestProductText, required String productDescriptionText, required String dateText, }) { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnPrimaryContainer, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: productImage, height: 48.adaptSize, width: 48.adaptSize, radius: BorderRadius.circular(5.h), margin: EdgeInsets.only(bottom: 40.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(bestProductText, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 6.v), SizedBox(width: 269.h, child: Text(productDescriptionText, maxLines: 2, overflow: TextOverflow.ellipsis, style: TextStyle(color: appTheme.blueGray300, fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), SizedBox(height: 1.v), Text(dateText, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
