import 'models/notification_offer_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/notification_offer_provider.dart';class NotificationOfferScreen extends StatefulWidget {const NotificationOfferScreen({Key? key}) : super(key: key);

@override NotificationOfferScreenState createState() =>  NotificationOfferScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => NotificationOfferProvider(), child: NotificationOfferScreen()); } 
 }
class NotificationOfferScreenState extends State<NotificationOfferScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 12.v), child: Column(children: [_buildOfferItemRow(context, offer: "lbl_the_best_title".tr, description: "msg_culpa_cillum_consectetur".tr, time: "msg_april_30_2014_1_01".tr), _buildOfferItemRow(context, offer: "msg_summer_offer_98".tr, description: "msg_culpa_cillum_consectetur".tr, time: "msg_april_30_2014_1_01".tr), SizedBox(height: 5.v), _buildOfferItemRow(context, offer: "msg_special_offer_25".tr, description: "msg_culpa_cillum_consectetur".tr, time: "msg_april_30_2014_1_01".tr)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "lbl_notification".tr, margin: EdgeInsets.only(left: 12.h))); } 
/// Common widget
Widget _buildOfferItemRow(BuildContext context, {required String offer, required String description, required String time, }) { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnPrimaryContainer, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSort, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 94.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(offer, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 10.v), SizedBox(width: 305.h, child: Text(description, maxLines: 3, overflow: TextOverflow.ellipsis, style: TextStyle(color: appTheme.blueGray300, fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), SizedBox(height: 5.v), Text(time, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
