import '../dashboard_page/widgets/arrowright_item_widget.dart';import '../dashboard_page/widgets/megasaleheader_item_widget.dart';import '../dashboard_page/widgets/offerbanner_item_widget.dart';import '../dashboard_page/widgets/productitem_item_widget.dart';import '../dashboard_page/widgets/products_item_widget.dart';import 'models/arrowright_item_model.dart';import 'models/dashboard_model.dart';import 'models/megasaleheader_item_model.dart';import 'models/offerbanner_item_model.dart';import 'models/productitem_item_model.dart';import 'models/products_item_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_trailing_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'provider/dashboard_provider.dart';class DashboardPage extends StatefulWidget {const DashboardPage({Key? key}) : super(key: key);

@override DashboardPageState createState() =>  DashboardPageState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => DashboardProvider(), child: DashboardPage()); } 
 }
class DashboardPageState extends State<DashboardPage> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: Padding(padding: EdgeInsets.only(left: 16.h, bottom: 5.v), child: Column(children: [_buildOfferBannerTitle(context), SizedBox(height: 25.v), _buildCategories(context), SizedBox(height: 37.v), _buildFlashSale(context), SizedBox(height: 23.v), _buildMegaSale(context), SizedBox(height: 29.v), CustomImageView(imagePath: ImageConstant.imgRecomendedProduct, height: 206.v, width: 343.h, radius: BorderRadius.circular(5.h), alignment: Alignment.centerLeft), SizedBox(height: 16.v), _buildProducts(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 32.h, top: 20.v, bottom: 20.v)), title: AppbarTitle(text: "lbl_search_product".tr, margin: EdgeInsets.only(left: 8.h), onTap: () {onTapSearchProduct(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLoveIcon, margin: EdgeInsets.only(left: 16.h, top: 16.v, right: 16.h), onTap: () {onTapLoveIcon(context);}), Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 16.h, top: 16.v, right: 32.h), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgNotificationIcon, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center, onTap: () {onTapImgNotificationIcon(context);}), CustomImageView(imagePath: ImageConstant.imgClosePink300, height: 8.adaptSize, width: 8.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(left: 14.h, right: 2.h, bottom: 16.v))]))]); } 
/// Section Widget
Widget _buildOfferBannerTitle(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 16.h), child: Consumer<DashboardProvider>(builder: (context, provider, child) {return CarouselSlider.builder(options: CarouselOptions(height: 206.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {provider.sliderIndex = index;}), itemCount: provider.dashboardModelObj.offerbannerItemList.length, itemBuilder: (context, index, realIndex) {OfferbannerItemModel model = provider.dashboardModelObj.offerbannerItemList[index]; return OfferbannerItemWidget(model);});})), SizedBox(height: 16.v), Consumer<DashboardProvider>(builder: (context, provider, child) {return Container(height: 8.v, margin: EdgeInsets.only(left: 135.h), child: AnimatedSmoothIndicator(activeIndex: provider.sliderIndex, count: provider.dashboardModelObj.offerbannerItemList.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: theme.colorScheme.primary.withOpacity(1), dotColor: appTheme.blue50, dotHeight: 8.v, dotWidth: 8.h)));})]); } 
/// Section Widget
Widget _buildCategories(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 16.h), child: _buildFlashSaleHeader(context, flashSaleText: "lbl_category".tr, seeMoreText: "lbl_more_category".tr, onTapSeeMoreText: () {onTapTxtSeeMoreText(context);})), SizedBox(height: 10.v), SizedBox(height: 94.v, child: Consumer<DashboardProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: provider.dashboardModelObj.arrowrightItemList.length, itemBuilder: (context, index) {ArrowrightItemModel model = provider.dashboardModelObj.arrowrightItemList[index]; return ArrowrightItemWidget(model);});}))]); } 
/// Section Widget
Widget _buildProductItem(BuildContext context) { return SizedBox(height: 238.v, child: Consumer<DashboardProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: provider.dashboardModelObj.productitemItemList.length, itemBuilder: (context, index) {ProductitemItemModel model = provider.dashboardModelObj.productitemItemList[index]; return ProductitemItemWidget(model);});})); } 
/// Section Widget
Widget _buildFlashSale(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 16.h), child: _buildFlashSaleHeader(context, flashSaleText: "lbl_flash_sale".tr, seeMoreText: "lbl_see_more".tr, onTapFlashSaleHeader: () {onTapFlashSaleHeader(context);})), SizedBox(height: 12.v), _buildProductItem(context)]); } 
/// Section Widget
Widget _buildMegaSaleHeader(BuildContext context) { return SizedBox(height: 238.v, child: Consumer<DashboardProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: provider.dashboardModelObj.megasaleheaderItemList.length, itemBuilder: (context, index) {MegasaleheaderItemModel model = provider.dashboardModelObj.megasaleheaderItemList[index]; return MegasaleheaderItemWidget(model);});})); } 
/// Section Widget
Widget _buildMegaSale(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 16.h), child: _buildFlashSaleHeader(context, flashSaleText: "lbl_mega_sale".tr, seeMoreText: "lbl_see_more".tr)), SizedBox(height: 10.v), _buildMegaSaleHeader(context)]); } 
/// Section Widget
Widget _buildProducts(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 16.h), child: Consumer<DashboardProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 283.v, crossAxisCount: 2, mainAxisSpacing: 13.h, crossAxisSpacing: 13.h), physics: NeverScrollableScrollPhysics(), itemCount: provider.dashboardModelObj.productsItemList.length, itemBuilder: (context, index) {ProductsItemModel model = provider.dashboardModelObj.productsItemList[index]; return ProductsItemWidget(model);});}))); } 
/// Common widget
Widget _buildFlashSaleHeader(BuildContext context, {required String flashSaleText, required String seeMoreText, Function? onTapFlashSaleHeader, Function? onTapSeeMoreText, }) { return GestureDetector(onTap: () {onTapFlashSaleHeader!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(flashSaleText, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), GestureDetector(onTap: () {onTapSeeMoreText!.call();}, child: Text(seeMoreText, style: TextStyle(color: theme.colorScheme.primary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)))])); } 
/// Navigates to the searchScreen when the action is triggered.
onTapSearchProduct(BuildContext context) { NavigatorService.pushNamed(AppRoutes.searchScreen, ); } 
/// Navigates to the favoriteProductScreen when the action is triggered.
onTapLoveIcon(BuildContext context) { NavigatorService.pushNamed(AppRoutes.favoriteProductScreen, ); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapImgNotificationIcon(BuildContext context) { NavigatorService.pushNamed(AppRoutes.notificationScreen, ); } 
/// Navigates to the listCategoryScreen when the action is triggered.
onTapTxtSeeMoreText(BuildContext context) { NavigatorService.pushNamed(AppRoutes.listCategoryScreen, ); } 
/// Navigates to the superFlashSaleScreen when the action is triggered.
onTapFlashSaleHeader(BuildContext context) { NavigatorService.pushNamed(AppRoutes.superFlashSaleScreen, ); } 
 }
