import '../product_detail_page/widgets/blue_item_widget.dart';import '../product_detail_page/widgets/products1_item_widget.dart';import '../product_detail_page/widgets/recomended_item_widget.dart';import 'models/blue_item_model.dart';import 'models/product_detail_model.dart';import 'models/products1_item_model.dart';import 'models/recomended_item_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/custom_elevated_button.dart';import 'package:blackevil2401_s_application3/widgets/custom_rating_bar.dart';import 'package:flutter/material.dart';import 'provider/product_detail_provider.dart';class ProductDetailPage extends StatefulWidget {const ProductDetailPage({Key? key}) : super(key: key);

@override ProductDetailPageState createState() =>  ProductDetailPageState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ProductDetailProvider(), child: ProductDetailPage()); } 
 }
class ProductDetailPageState extends State<ProductDetailPage> with  AutomaticKeepAliveClientMixin<ProductDetailPage> {@override bool get wantKeepAlive =>  true;

@override void initState() { super.initState();NavigatorService.pushNamed(AppRoutes.searchScreen, ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSelectColorSection(context), SizedBox(height: 25.v), _buildSpecificationsSection(context), SizedBox(height: 21.v), _buildReviewSection(context), SizedBox(height: 23.v), _buildYouMightAlsoLikeSection(context), SizedBox(height: 21.v), CustomElevatedButton(text: "lbl_add_to_cart".tr, margin: EdgeInsets.only(right: 16.h))]))]))))); } 
/// Section Widget
Widget _buildSelectColorSection(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_select_color".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 12.v), SizedBox(height: 48.v, child: Consumer<ProductDetailProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: provider.productDetailModelObj.blueItemList.length, itemBuilder: (context, index) {BlueItemModel model = provider.productDetailModelObj.blueItemList[index]; return BlueItemWidget(model);});}))]); } 
/// Section Widget
Widget _buildSpecificationsSection(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 16.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_specification".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))), SizedBox(height: 12.v), _buildStyleSection(context, styleText: "lbl_shown".tr, styleCodeText: "msg_laser_blue_anth".tr), SizedBox(height: 14.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildStyleSection(context, styleText: "lbl_style".tr, styleCodeText: "lbl_cd0113_400".tr), SizedBox(height: 19.v), Container(width: 320.h, margin: EdgeInsets.only(right: 23.h), child: Text("msg_the_nike_air_max".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: TextStyle(color: appTheme.blueGray300, fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400)))])])); } 
/// Section Widget
Widget _buildReviewSection(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildStyleSection(context, styleText: "lbl_review_product".tr, styleCodeText: "lbl_see_more".tr, onTapStyleCodeText: () {onTapTxtStyleCodeText(context);}), SizedBox(height: 8.v), Row(children: [CustomRatingBar(initialRating: 4, itemSize: 16), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_4_5".tr, style: TextStyle(color: appTheme.blueGray300, fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700))), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_5_review".tr, style: TextStyle(color: appTheme.blueGray300, fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400)))]), SizedBox(height: 16.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgProfilePicture, height: 48.adaptSize, width: 48.adaptSize, radius: BorderRadius.circular(24.h)), Padding(padding: EdgeInsets.only(left: 16.h, top: 2.v, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_james_lawson".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 4.v), CustomRatingBar(initialRating: 4, itemSize: 16)]))]), SizedBox(height: 18.v), SizedBox(width: 339.h, child: Text("msg_air_max_are_always".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: TextStyle(color: appTheme.blueGray300, fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), SizedBox(height: 13.v), SizedBox(height: 72.v, child: Consumer<ProductDetailProvider>(builder: (context, provider, child) {return ListView.separated(padding: EdgeInsets.only(right: 103.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: provider.productDetailModelObj.products1ItemList.length, itemBuilder: (context, index) {Products1ItemModel model = provider.productDetailModelObj.products1ItemList[index]; return Products1ItemWidget(model);});})), SizedBox(height: 16.v), Text("msg_december_10_2016".tr, style: TextStyle(color: appTheme.blueGray300, fontSize: 10.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))])); } 
/// Section Widget
Widget _buildYouMightAlsoLikeSection(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_you_might_also_like".tr, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w700)), SizedBox(height: 11.v), SizedBox(height: 238.v, child: Consumer<ProductDetailProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: provider.productDetailModelObj.recomendedItemList.length, itemBuilder: (context, index) {RecomendedItemModel model = provider.productDetailModelObj.recomendedItemList[index]; return RecomendedItemWidget(model);});}))]); } 
/// Common widget
Widget _buildStyleSection(BuildContext context, {required String styleText, required String styleCodeText, Function? onTapStyleCodeText, }) { return Row(children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(styleText, style: TextStyle(color: theme.colorScheme.onPrimary.withOpacity(1), fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))), GestureDetector(onTap: () {onTapStyleCodeText!.call();}, child: Padding(padding: EdgeInsets.only(left: 234.h), child: Text(styleCodeText, style: TextStyle(color: appTheme.blueGray300, fontSize: 12.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400))))]); } 
/// Navigates to the reviewProductScreen when the action is triggered.
onTapTxtStyleCodeText(BuildContext context) { NavigatorService.pushNamed(AppRoutes.reviewProductScreen, ); } 
 }
