import '../choose_credit_or_debit_card_screen/widgets/user_item_widget.dart';import 'models/choose_credit_or_debit_card_model.dart';import 'models/user_item_model.dart';import 'package:blackevil2401_s_application3/core/app_export.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_title.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/appbar_trailing_image.dart';import 'package:blackevil2401_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:blackevil2401_s_application3/widgets/custom_elevated_button.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'provider/choose_credit_or_debit_card_provider.dart';class ChooseCreditOrDebitCardScreen extends StatefulWidget {const ChooseCreditOrDebitCardScreen({Key? key}) : super(key: key);

@override ChooseCreditOrDebitCardScreenState createState() =>  ChooseCreditOrDebitCardScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ChooseCreditOrDebitCardProvider(), child: ChooseCreditOrDebitCardScreen()); } 
 }
class ChooseCreditOrDebitCardScreenState extends State<ChooseCreditOrDebitCardScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 27.v), child: Column(children: [Consumer<ChooseCreditOrDebitCardProvider>(builder: (context, provider, child) {return CarouselSlider.builder(options: CarouselOptions(height: 190.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {provider.sliderIndex = index;}), itemCount: provider.chooseCreditOrDebitCardModelObj.userItemList.length, itemBuilder: (context, index, realIndex) {UserItemModel model = provider.chooseCreditOrDebitCardModelObj.userItemList[index]; return UserItemWidget(model);});}), SizedBox(height: 16.v), Consumer<ChooseCreditOrDebitCardProvider>(builder: (context, provider, child) {return SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: provider.sliderIndex, count: provider.chooseCreditOrDebitCardModelObj.userItemList.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: theme.colorScheme.primary.withOpacity(1), dotColor: appTheme.blue50, dotHeight: 8.v, dotWidth: 8.h)));}), SizedBox(height: 5.v)])), bottomNavigationBar: _buildPayButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "lbl_choose_card".tr, margin: EdgeInsets.only(left: 12.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgPlusIcon, margin: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v))]); } 
/// Section Widget
Widget _buildPayButton(BuildContext context) { return CustomElevatedButton(text: "lbl_pay_766_86".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 50.v), onPressed: () {onTapPayButton(context);}); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the successScreen when the action is triggered.
onTapPayButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.successScreen, ); } 
 }
